import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ExampleClientComponent from "./(other)/example-client-component";
import Notification from "./(other)/notification";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  manifest: "/manifest.json",
  title: 'Document',
  description: 'Generated by create next app',
  // icons: [{ rel: 'icon', url: Favicon.src }],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <ExampleClientComponent />
        <Notification />
      </body>
    </html>
  );
}
